# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Alex <aorlov@fastly.com>"]
description = "EWAF without Delivery service"
language = "javascript"
manifest_version = 2
name = "xxx"
service_id = "XXXXX"

[local_server]

[local_server.backends]

[local_server.backends.waf]
override_host = "waf.xxx.ch"
url = "https://waf.xxx.ch"

[local_server.backends.test]
override_host = "se--xxx--xxx.edgecompute.app"
url = "https://se--xxx--xxx.edgecompute.app"

[local_server.object_store]
[[local_server.object_store.object-store]]
data = "preDefinedObjectStoreDataValue"
key = "preDefinedObjectStoreKey"

[local_server.config_stores]
#[local_server.config_stores.config_store]
#apiKey = "testkey"
[local_server.config_stores.meta]
format = "inline-toml"
[local_server.config_stores.meta.contents]
disallowedIps = "127.0.0.2"
"whitelist.url1" = "https://example1.com"
[local_server.config_stores.env]
format = "inline-toml"

[local_server.config_stores.env.contents]
apiKey = "0815"
"whitelist.url" = "https://example.com"

[scripts]
build = "npm exec js-compute-runtime ./src/index.js ./bin/main.wasm"

[setup]

[setup.object_stores]
[setup.object_stores.store]
description = "preDefinedObjectStoreKey"
[setup.object_stores.my-store.items]
[setup.object_stores.my-store.items.preDefinedObjectStoreKey]
description = "my preDefinedObjectStoreKey description"
value = "my preDefinedObjectStoreKey"

[setup.backends]

[setup.backends.cdn-origin]
address = "cdn-origin.xxx.de"
description = "CDN Origin"
port = 443

[setup.backends.ewaf]
address = "se--xxx--xxx.edgecompute.app"
description = "EWAF"
port = 443

[setup.config_stores]

[setup.config_stores.dict]

[setup.log_endpoints]

[setup.log_endpoints.elkfastly]
provider = "Elasticsearch"
